version: '3'
services:

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8088:8088"
    volumes:
      - ./:/var/www/dexart
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/sites/:/etc/nginx/conf.d/
    networks:
      - dexart-network


  #PHP Service
  dexart:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SERVICE_NAME: dexart
      SERVICE_TAGS: dev
    working_dir: /var/www/dexart
    volumes:
      - ./:/var/www/dexart
      - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - dexart-network

networks:
  dexart-network:
    driver: bridge
